      fix refrence bug          In torch==1.5, the import of the API has changed. Although it does not interrupt the operation of the program, it seems to me to be an implicit error and may throw an exception in later versions. 
     vid_path, vid_writer = None, None      if webcam:          view_img = True         torch.backends.cudnn.benchmark = True  # set True to speed up constant image size inference         cudnn.benchmark = True  # set True to speed up constant image size inference          dataset = LoadStreams(source, img_size=imgsz)      else:          save_img = True 
